# --------------------------------------------------------------------------------------------------------
# PlayStation 2 Basic Boot Loader Extended config file by Berion              2026-07-16 [MC/MMCE/BDM SAS]
# --------------------------------------------------------------------------------------------------------

KEY_READ_WAIT_TIME = 0
SKIP_PS2LOGO = 0
LOGO_DISPLAY = 3
OSDHISTORY_READ = 1
EJECT_TRAY = 0
CDROM_DISABLE_GAMEID = 0
APP_GAMEID = 1
PS1DRV_ENABLE_FAST = 0
PS1DRV_ENABLE_SMOOTH = 0
PS1DRV_USE_PS1VN = 1

LOAD_IRX_E1 = 
LOAD_IRX_E2 = 
LOAD_IRX_E3 = 
LOAD_IRX_E4 = 
LOAD_IRX_E5 = 

NAME_AUTO = FMCB/OSDM
LK_AUTO_E1 = mc?:/SYS_OSDMENU/OSDMENU.ELF
LK_AUTO_E2 = mc?:/SYS_FMCB-1966/FMCB-1966.ELF
LK_AUTO_E3 = mc?:/SYS_FMCB-18C/FMCB-18C.ELF
LK_AUTO_E4 = mc?:/SYS_FMCBD-1966/FMCBD-1966.ELF
LK_AUTO_E5 = mc?:/SYS_FMCBD-18C/FMCBD-18C.ELF
LK_AUTO_E6 = 
LK_AUTO_E7 = 
LK_AUTO_E8 = 
LK_AUTO_E9 = mc?:/BOOT/BOOT2.ELF

NAME_SELECT = XEB+
LK_SELECT_E1 = usb:/XEBPLUS/XEBPLUS_XMAS.ELF
LK_SELECT_E2 = usb:/XEBPLUS/XEBPLUS.ELF
LK_SELECT_E3 = 
LK_SELECT_E4 = 
LK_SELECT_E5 = 
LK_SELECT_E6 = 
LK_SELECT_E7 = 
LK_SELECT_E8 = 
LK_SELECT_E9 = 

NAME_START = OSD-XMB
LK_START_E1 = mc?:/APP_OSDXMB/OSDXMB.ELF
LK_START_E2 = mc?:/XMB/OSDXMB.ELF
LK_START_E3 = usb:/OSDXMB/OSDXMB.ELF
LK_START_E4 = 
LK_START_E5 = 
LK_START_E6 = 
LK_START_E7 = 
LK_START_E8 = 
LK_START_E9 = 

NAME_L1 = OPL
LK_L1_E1 = mc?:/APP_OPL/OPL.ELF
LK_L1_E2 = mmce0:/APPS/APP_OPL/OPL.ELF
LK_L1_E3 = mx4sio:/APPS/APP_OPL/OPL.ELF
LK_L1_E4 = 
LK_L1_E5 = 
LK_L1_E6 = 
LK_L1_E7 = 
LK_L1_E8 = 
LK_L1_E9 = 

NAME_L2 = wOPL
LK_L2_E1 = mc?:/APP_WOPL/WOPL.ELF
LK_L2_E2 = mmce0:/APP_WOPL/WOPL.ELF
LK_L2_E3 = mx4sio:/APP_WOPL/WOPL.ELF
LK_L2_E4 = 
LK_L2_E5 = 
LK_L2_E6 = 
LK_L2_E7 = 
LK_L2_E8 = 
LK_L2_E9 = 

NAME_L3 = RiptOPL
LK_L3_E1 = mc?:/APP_RIPTOPL/RIPTOPL.ELF
LK_L3_E2 = mmce0:/APP_RIPTOPL/RIPTOPL.ELF
LK_L3_E3 = mx4sio:/APP_RIPTOPL/RIPTOPL.ELF
LK_L3_E4 = 
LK_L3_E5 = 
LK_L3_E6 = 
LK_L3_E7 = 
LK_L3_E8 = 
LK_L3_E9 = 

NAME_R1 = uLaunchELF
LK_R1_E1 = mc?:/APP_ULE/ULE.ELF
LK_R1_E2 = mmce0:/APP_ULE/ULE.ELF
LK_R1_E3 = mx4sio:/APP_ULE/ULE.ELF
LK_R1_E4 = 
LK_R1_E5 = 
LK_R1_E6 = 
LK_R1_E7 = 
LK_R1_E8 = 
LK_R1_E9 = 

NAME_R2 = wLaunchELF ISR
LK_R2_E1 = mc?:/APP_WLE-ISR-XF/WLE-ISR-XF.ELF
LK_R2_E2 = mmce0:/APP_WLE-ISR-XF/WLE-ISR-XF.ELF
LK_R2_E3 = mx4sio:/APP_WLE-ISR-XF/WLE-ISR-XF.ELF
LK_R2_E4 = 
LK_R2_E5 = 
LK_R2_E6 = 
LK_R2_E7 = 
LK_R2_E8 = 
LK_R2_E9 = 

NAME_R3 = wLaunchELF R3Z
LK_R3_E1 = mc?:/APP_WLE-R3Z/WLE-R3Z.ELF
LK_R3_E2 = mmce0:/APP_WLE-R3Z/WLE-R3Z.ELF
LK_R3_E3 = mx4sio:/APP_WLE-R3Z/WLE-R3Z.ELF
LK_R3_E4 = 
LK_R3_E5 = 
LK_R3_E6 = 
LK_R3_E7 = 
LK_R3_E8 = 
LK_R3_E9 = 

NAME_CROSS = ESR Launcher
LK_CROSS_E1 = mc?:/APP_ESR-LAUNCHER/ESR-LAUNCHER.ELF
LK_CROSS_E2 = mmce0:/APP_ESR-LAUNCHER/ESR-LAUNCHER.ELF
LK_CROSS_E3 = mx4sio:/APP_ESR-LAUNCHER/ESR-LAUNCHER.ELF
LK_CROSS_E4 = 
LK_CROSS_E5 = 
LK_CROSS_E6 = 
LK_CROSS_E7 = 
LK_CROSS_E8 = 
LK_CROSS_E9 = 

NAME_SQUARE = DKWDRV
LK_SQUARE_E1 = mc?:/PS1_DKWDRV/DKWDRV.ELF
LK_SQUARE_E2 = mmce0:/PS1_DKWDRV/DKWDRV.ELF
LK_SQUARE_E3 = mx4sio:/PS1_DKWDRV/DKWDRV.ELF
LK_SQUARE_E4 = 
LK_SQUARE_E5 = 
LK_SQUARE_E6 = 
LK_SQUARE_E7 = 
LK_SQUARE_E8 = 
LK_SQUARE_E9 = 

NAME_TRIANGLE = 
LK_TRIANGLE_E1 = 
LK_TRIANGLE_E2 = 
LK_TRIANGLE_E3 = 
LK_TRIANGLE_E4 = 
LK_TRIANGLE_E5 = 
LK_TRIANGLE_E6 = 
LK_TRIANGLE_E7 = 
LK_TRIANGLE_E8 = 
LK_TRIANGLE_E9 = 

NAME_CIRCLE = POPSloader
LK_CIRCLE_E1 = mc?:/PS1_POPSLOADER/POPSLOADER.ELF
LK_CIRCLE_E2 = 
LK_CIRCLE_E3 = 
LK_CIRCLE_E4 = 
LK_CIRCLE_E5 = 
LK_CIRCLE_E6 = 
LK_CIRCLE_E7 = 
LK_CIRCLE_E8 = 
LK_CIRCLE_E9 = 

NAME_UP = PS2 Browser
LK_UP_E1 = $OSDSYS
LK_UP_E2 = 
LK_UP_E3 = 
LK_UP_E4 = 
LK_UP_E5 = 
LK_UP_E6 = 
LK_UP_E7 = 
LK_UP_E8 = 
LK_UP_E9 = 

NAME_DOWN = Test Mode
LK_DOWN_E1 = rom0:TESTMODE
LK_DOWN_E2 = 
LK_DOWN_E3 = 
LK_DOWN_E4 = 
LK_DOWN_E5 = 
LK_DOWN_E6 = 
LK_DOWN_E7 = 
LK_DOWN_E8 = 
LK_DOWN_E9 = 

NAME_LEFT = Disc
LK_LEFT_E1 = $CDVD
LK_LEFT_E2 = 
LK_LEFT_E3 = 
LK_LEFT_E4 = 
LK_LEFT_E5 = 
LK_LEFT_E6 = 
LK_LEFT_E7 = 
LK_LEFT_E8 = 
LK_LEFT_E9 = 

NAME_RIGHT = Disc (logo bypass)
LK_RIGHT_E1 = $CDVD_NO_PS2LOGO
LK_RIGHT_E2 = 
LK_RIGHT_E3 = 
LK_RIGHT_E4 = 
LK_RIGHT_E5 = 
LK_RIGHT_E6 = 
LK_RIGHT_E7 = 
LK_RIGHT_E8 = 
LK_RIGHT_E9 = 

